### ISSUE TITLE
infix functions in generated decoders

### ISSUE THREAD

**Issue by ericgj** [tiziano88/elm-protobuf#10]
Given infix functions are problematic in Elm at the moment (they cause conflicts if any 2 libraries define the same function), and may be going away except for in core libraries in 0.19, would it be possible to replace the `(<$>)` and `(<*>)` in the generated decoders?  

(Sorry if this is already done, I have not looked at the implementation, just the expected output in the tests.)

**Comment by tiziano88** [comment]
Yes I agree, we should probably use a style similar to https://github.com/NoRedInk/elm-decode-pipeline instead of the infix operators, I may get to it at some point but contributions are welcome :)

**Comment by ericgj** [comment]
Just discovered [you already did this](https://github.com/tiziano88/elm-protobuf/commit/5927191321a12545ffa718f0ed359fc5b14da3b4#diff-eeb546dfa660596b8362c6c0a6efa741) !   The expected output in the `go_tests` still have the infix functions, don't know if these are not used anymore or need to be updated.
