### ISSUE TITLE
Map support

### ISSUE THREAD

**Issue by mxinden** [tiziano88/elm-protobuf#3]
Are there any steps planned on supporting [`map`](https://developers.google.com/protocol-buffers/docs/proto#maps) in the near future? 

We are currently looking into GRPC and its integration with Elm for [Prometheus Alertmanager](https://github.com/prometheus/alertmanager). `Map` support would be a crucial feature for us. (See [PR](https://github.com/prometheus/alertmanager/pull/698))

**Comment by tiziano88** [comment]
Map support should not be too hard, I could look into it and get it done probably by end of April (sooner if anyone is willing to help :) ).

Although AFAICT the gRPC protocol is binary, not JSON, so not sure you would be able to use this library to connect to a gRPC server. Could you confirm?

**Comment by mxinden** [comment]
@tiziano88 thanks for your quick reply!

Our idea is to serve both a JSON api and a gRPC api. With our Elm front-end we would be targeting the JSON api and use the decoders generated by *elm-protobuf* to decode the JSON responses by the api. If I understand the library description correctly this would be the way to go, right?

**Comment by tiziano88** [comment]
Yes, sounds like a good plan :+1: I'll look into adding map support, will make sure to update this as I go about it.

**Comment by mxinden** [comment]
We will be using [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) to serve the JSON API. This means for us, that we need to interpret the `.proto` file with this package the same way as the grpc-gateway plugin interprets it.

What is your use case for this package? What kind of API are you targeting? Are you using the grpc-gateway plugin as well?

Thanks for your help!

**Comment by tiziano88** [comment]
I did not know about grpc-gateway, thanks for mentioning it, looks very interesting and I should probably add a link to it in the documentation! My longer-term plan is to actually support proto binary encoding and native gRPC, but AFAICT Elm does not support HTTP2 yet (which is needed for gRPC), so it may take a while until that happens.

**Comment by mxinden** [comment]
@tiziano88 We have decided to use the gRPC-gateway to generate a Swagger spec. From this Swagger spec ware using [swagger-elm](https://github.com/ahultgren/swagger-elm) to generate our front-end client. I have contributed the the map support in the that library instead of this one (See [issue](https://github.com/ahultgren/swagger-elm/issues/10)).

**Comment by karlseguin** [comment]
The current implementation limits map keys to strings. The protocol spec also allows any integral spec. Any reason for the limitation?
