### ISSUE TITLE
LIst of items not decoding

### ISSUE THREAD

**Issue by donpdonp** [tiziano88/elm-protobuf#4]
First thanks for the elm protobuf compiler, its fantastic and lets me roll my own websocket/json-rpc with protobuf+elm on one side and protobuf+go on the other. The compiled elm has been trouble-free until I tried to decode a list of objects (a "Schedule").

the js console shows elm received some json of apparently the right format
```
response: { id = "90de-18f43f9f486f", method = "ScheduleListResponse", object = { Ok = True, Schedules = { 0 = { Id = "schedules-877d-76499fe253ae", AccountId = "accounts-b8b0-6d34a035a65e", AlgorithmId = "noop", Status = "active" } } } }
```
after calling `scheduleListResponseDecoder response.object`, the decoded object, always has an empty array for Schedules.

```
ScheduleListResponseMsg { ok = True, message = "", schedules = [] }
```

the ScheduleListResponse protbuf is defined as
```protobuf
import "proto/schedule.proto";

message ScheduleListResponse {
  bool Ok = 1;
  string Message = 2;
  repeated Schedule Schedules = 3;
}
```

and the Schedule is
```protobuf
message Schedule {
  string Id = 1;
  string AccountId = 2;
  string AlgorithmId = 3;
  string Status = 4;
}
```
the Elm for ScheduleListResponse also looks good
```elm
type alias ScheduleListResponse =
    { ok : Bool -- 1
    , message : String -- 2
    , schedules : List Schedule -- 3
    }


scheduleListResponseDecoder : JD.Decoder ScheduleListResponse
scheduleListResponseDecoder =
    JD.lazy <| \_ -> decode ScheduleListResponse
        |> required "Ok" JD.bool False
        |> required "Message" JD.string ""
        |> repeated "Schedules" scheduleDecoder
```

any ideas what might be wrong?

**Comment by tiziano88** [comment]
Should be fixed now, thanks a lot!
