### ISSUE TITLE
enum as int32

### ISSUE THREAD

**Issue by donpdonp** [tiziano88/elm-protobuf#6]
I'm using protoc with elm and go to pass data structures back and forth over websocket/json. Its been going great until I tried using enums. To my delight, the elm module uses the string value of each enum option. Unfortunately, the go (and crystal) code generators use the int32 form of an enum option. So `{"status":3}` does not decode on the elm side, and `{"status":"ready"}` does not decode on the go side Is there a way to get the generated elm code to use the int? I'd rather use the string val name but it appears int is more canonical, and possibly a win for space efficiency.

**Comment by tiziano88** [comment]
I'm not at my computer now, but I believe go emits strings by default? See https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L63

Will double check later anyway

**Comment by tiziano88** [comment]
In fact, the proto3 specification describes that the JSON representation of enums is the name of the enum values: https://developers.google.com/protocol-buffers/docs/proto3#json .

So it seems that Elm is doing the right thing, but your Go program is not? BTW, are you sure you are using the jsonpb package for that? Note that using the standard Go json package with protos does not work correctly.

**Comment by donpdonp** [comment]
Here's what I'm seeing.
```protobuf
syntax = "proto3";
package proto;

message Schedule {
(...)
  States Status = 4;
  enum States {
    unknown = 0;
    stopped = 1;
    running = 2;
  }
}
```

```
$ protoc3/bin/protoc --go_out=go
```

the field in go is an int

```go
type Schedule_States int32
type Schedule struct {
	Status       Schedule_States `protobuf:"varint,4,opt,name=Status,enum=proto.Schedule_States" json:"
Status,omitempty"`
```

and over the wire (it uses the protobuf json serializer)
```
{  Status = 1, ...
```

**Comment by donpdonp** [comment]
I think I found some go docs that will help. The elm side looks good as-is. Thanks.

**Comment by donpdonp** [comment]
followup: jsonpb was being used for reading json but not for writing json. Now I'm getting enum string values. sigh. thanks for the help.

**Comment by tiziano88** [comment]
No problem at all, thanks for reporting and for attempting a fix! Much appreciated

**Comment by donpdonp** [comment]
Is there a way to take an elm enum-type and get its string name? The encoder returns a JE.value which at best I can turn into "enum-option" with the quotes since its JSON encoded, when I'm looking for a simple elm string.

**Comment by tiziano88** [comment]
Do you mean like the value in https://github.com/tiziano88/elm-protobuf/blob/master/protoc-gen-elm/go_tests/testdata/repeated/expected_output/Repeated.elm#L88 ? That's not currently exposed, but I can think about it, may I ask what your use case is? It may help to come up with a readable name for such a function :) (I really wish Elm had typeclasses for something like this)

**Comment by donpdonp** [comment]
I'd like to be able to display to the user the name of the particular enum value, so I need a string to represent that. 

```protobuf
  enum States {
    unknown = 0;
    stopped = 1;
    running = 2;
  }
```

in elm I've got
```elm
type Schedule_States
    = Schedule_Unknown -- 0
    | Schedule_Stopped -- 1
    | Schedule_Running -- 2
```

I'm trying to display some html with `text s.state` where s.state is for example `Schedule_Running`, but text needs the string form of that value.
